# Generated by Django 2.1.7 on 2019-05-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Micropost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micropost_id', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('update_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
