# Generated by Django 2.1.7 on 2019-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micropost',
            name='id',
        ),
        migrations.AlterField(
            model_name='micropost',
            name='micropost_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
