# Generated by Django 2.1.7 on 2019-05-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microposts', '0002_auto_20190511_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='micropost',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='micropost',
            name='micropost_id',
        ),
        migrations.RemoveField(
            model_name='micropost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='micropost',
            name='update_date',
        ),
        migrations.AddField(
            model_name='micropost',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
